### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by thudzj** [Harry24k/bayesian-neural-network-pytorch#1]
Hi Harry,

It is nice to see your work on designing modules for building BNNs. I have checked the codes and I am impressive. I appreciate it if you could share with me the testing code to build and train a simple BNN with these codes.  Thanks a lot!

Zhijie

**Comment by Harry24k** [comment]
Hello Zhijie,

I'm happy to this work is useful to you.

This repositroy is still under reconstruction for double checking errors.

However, simple demos will be uploaded soon, at least the end of this month.

Thank you!

Sincerely, Harry.

2019년 11월 7일 (목) 오후 2:45, Zhijie Deng <notifications@github.com>님이 작성:

**Comment by thudzj** [comment]
Thanks for the instant reply! Looking forward to the release.
