### ISSUE TITLE
KLloss and re-parameters

### ISSUE THREAD

**Issue by starsky68** [Harry24k/bayesian-neural-network-pytorch#2]
Can KLLoss and re-parameters be customized?

**Comment by Harry24k** [comment]
Sure. Any loss can be applied to Bayesian layers with weight_mu, weight_log_sigma, prior_mu and prior_sigma. Please refer [here](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/e6c6a858064319008912d3a91941a802769520ef/torchbnn/functional.py#L21).

In addition, parameters can be initialized after build as follows : https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/e6c6a858064319008912d3a91941a802769520ef/torchbnn/modules/linear.py#L51.

**Comment by starsky68** [comment]
I mean, I applied BNN to a new field. The klloss calculation method provided in this torchbnn does not perform well. I found a new calculation method myself. Will this new calculation method affect the theoretical basis of Bayesian neural networks? In other words, if you change the calculation method of klloss in torchbnn, can it be pushed in the Bayesian neural network? In Bayesian neural networks, there must be only one way to calculate klloss.

**Comment by Harry24k** [comment]
The loss is calculated under the normal distribution of weights. If you want to see the proof, please refer [here](https://arxiv.org/pdf/1810.01279.pdf). Thus, even if you parameterize the weights with other distribution like gamma, as far as I know, it is still BNN cause the weights are drawn from the distribution. However, the formula of loss function have to be changed too. Of course, you can change only one of them(weight distribution or loss) in code, but I'm not sure we can call the model as BNN in this case, theoretically.

**Comment by starsky68** [comment]
> The loss is calculated under the normal distribution of weights. If you want to see the proof, please refer [here](https://arxiv.org/pdf/1810.01279.pdf). Thus, even if you parameterize the weights with other distribution like gamma, as far as I know, it is still BNN cause the weights are drawn from the distribution. However, the formula of loss function have to be changed too. Of course, you can change only one of them(weight distribution or loss) in code, but I'm not sure we can call the model as BNN in this case, theoretically. Although, it seems like [some papers](https://arxiv.org/pdf/1711.04345.pdf) extended KL-divergence loss to other loss(ex. Alpha-divergence) and still call it bayesian.

Regarding variational Bayesian theory, I am a novice. My thought friend said that every item in the KL Loss formula in the variational Bayesian theory cannot be changed, otherwise the entire variational inference will not hold. I don't quite understand the difference between the KLloss provided in torchbnn and the KLloss in the variational autoencoder.
[https://github.com/hwalsuklee/tensorflow-mnist-VAE/blob/e7903ac398aa5fc3eec8470177abf6ef78d9cac1/vae.py#L82](url)

**Comment by Harry24k** [comment]
In BNN, we use N(mu, sigma) as prior distribution so the KLloss function is like [this](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/e6c6a858064319008912d3a91941a802769520ef/torchbnn/functional.py#L6). If mu=0 and sigma=1, it will be the same formula with [the KLloss in the variational autoencoder](https://github.com/hwalsuklee/tensorflow-mnist-VAE/blob/e7903ac398aa5fc3eec8470177abf6ef78d9cac1/vae.py#L82). However, all these formulas assumes 'the prior and posterior distribution are Gaussian'.  In other words, "KL Loss formula in the variational Bayesian theory cannot be changed." is true only when "the prior and posterior distribution are Gaussian."

**Comment by starsky68** [comment]
> In BNN, we use N(mu, sigma) as prior distribution so the KLloss function is like [this](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/e6c6a858064319008912d3a91941a802769520ef/torchbnn/functional.py#L6). If mu=0 and sigma=1, it will be the same formula with [the KLloss in the variational autoencoder](https://github.com/hwalsuklee/tensorflow-mnist-VAE/blob/e7903ac398aa5fc3eec8470177abf6ef78d9cac1/vae.py#L82). However, all these formulas assumes 'the prior and posterior distribution are Gaussian'. In other words, "KL Loss formula in the variational Bayesian theory cannot be changed." is true only when "the prior and posterior distribution are Gaussian."

Thank you very much for your reply. I really appreciate it. I understand. Can I understand it this way? KLLoss in variational autoencoder is a special form of KLLoss in BNN. So, can the formula of KLLoss in BNN be changed according to my intuition? If so, does it deviate from the theory of variation, or does it not conform to the theory of BNN?

**Comment by Harry24k** [comment]
I'm glad it was helpful. You can give variation to BNN by setting the prior and posterior distribution to what you want. But, it might be quite hard to get a neat formula. For example, in the case of gamma distribution, the KLLoss is as follows : https://stats.stackexchange.com/questions/11646/kullback-leibler-divergence-between-two-gamma-distributions. Further more, in practice, we multiply KLLoss by some weight or extend KLLoss to Alpha-divergence. I'm not sure we can say "These are definitely BNN.", but they are used frequently.

**Comment by Harry24k** [comment]
> In the model I made, I found a phenomenon. Based on BNN, when I added a formula to calculate the Euclidean distance between the prior and the posterior on the basis of the original klloss. My starting point is that since KLLoss can narrow the difference between the prior distribution and the posterior distribution, then I regard the prior (mu, sigma) as a point, and then the posterior (mu, sigma) as a group of points , And then calculate the difference between a priori and a posteriori, and then achieve the purpose of reducing the distance between the two. You can make the model perform better. Can you give an explanation or your opinion for this reason?

Based on my personal experience, the performance of BNN is highly dependent on data and hyper-parameters. Sometimes sigma=0.5 works well but sometimes it produces a useless model. I guess KLLoss is also key point of the performance. If you upload some code and situation, I can see it in more detail.

**Comment by starsky68** [comment]
> > In the model I made, I found a phenomenon. Based on BNN, when I added a formula to calculate the Euclidean distance between the prior and the posterior on the basis of the original klloss. My starting point is that since KLLoss can narrow the difference between the prior distribution and the posterior distribution, then I regard the prior (mu, sigma) as a point, and then the posterior (mu, sigma) as a group of points , And then calculate the difference between a priori and a posteriori, and then achieve the purpose of reducing the distance between the two. You can make the model perform better. Can you give an explanation or your opinion for this reason?
> 
> Based on my personal experience, the performance of BNN is highly dependent on data and hyper-parameters. Sometimes sigma=0.5 works well but sometimes it produces a useless model. I guess KLLoss is also an key point of the performance. If you upload code and environment, I can see it in more detail.



> > In the model I made, I found a phenomenon. Based on BNN, when I added a formula to calculate the Euclidean distance between the prior and the posterior on the basis of the original klloss. My starting point is that since KLLoss can narrow the difference between the prior distribution and the posterior distribution, then I regard the prior (mu, sigma) as a point, and then the posterior (mu, sigma) as a group of points , And then calculate the difference between a priori and a posteriori, and then achieve the purpose of reducing the distance between the two. You can make the model perform better. Can you give an explanation or your opinion for this reason?
> 
> Based on my personal experience, the performance of BNN is highly dependent on data and hyper-parameters. Sometimes sigma=0.5 works well but sometimes it produces a useless model. I guess KLLoss is also an key point of the performance. If you upload code and environment, I can see it in more detail.

[https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/e6c6a858064319008912d3a91941a802769520ef/torchbnn/functional.py#L18](url).Must this calculation be used there? Remove "torch.exp" and "math.exp" in my model, this will have better performance

**Comment by Harry24k** [comment]
That's interesting. I can't find any reason it makes better performance. Can you do experiment without KLLoss?

**Comment by starsky68** [comment]
> That's interesting. I can't find any reason it makes better performance. Can you do experiment without KLLoss?

By the way, ask you again. Without the use of klloss, the a priori at each layer also loses its function. At this time, only the a posteriori works. So, what kind of situation does this belong to?

**Comment by Harry24k** [comment]
In that case, the prior distribution would be only used for initialization of weights. Thus, the posteriori is no need to go closer to the priori. Still, weights are drawn from distributions so that we can't call this network as Neural Network, but at the same time, the meaning of using ELBO in the BNN is lost. Unfortunately, as I mentioned, I'm not sure this framework is BNN cause I couldn't find any papers treat this framework.

**Comment by starsky68** [comment]
> In that case, the prior distribution would be only used for initialization of weights. Thus, the posteriori is no need to go closer to the priori. Still, weights are drawn from distributions so that we can't call this network as Neural Network, but at the same time, the meaning of using ELBO in the BNN framework is lost. Unfortunately, as I mentioned, I'm not sure this framework is BNN cause I couldn't find any papers treat this framework. Maybe, it should be treated as one of the randomization skills.

https://github.com/xuanqing94/BayesianDefense/blob/c4c0be9b258f40130b40d6a6e009c459666f2722/main_vi.py#L97.Excuse me, why divide by 100 in this calculation formula.

**Comment by starsky68** [comment]
[https://github.com/kumar-shridhar/PyTorch-BayesianCNN/blob/81e6a354e2638cfad488a139dea4a432d9ad3578/layers/BBB/BBBLinear.py#L57](url).Here I only found that the exp operation is performed on the posterior sigma, but it seems that the exp operation is not performed on the prior.Or am I wrong?

**Comment by starsky68** [comment]
As you said above, it is definitely not a traditional neural network without using KLLoss, but it is not sure whether it is a BNN. Then the case of using KLLoss should be BNN. From the demos in the torchbnn project you provided, I tested the "iris" example. I found that the exp operation in the KLLoss calculation formula provided in the project seems to limit the final performance of the built model. I don’t know if I’m doing it properly. If you are interested, you can try it.

**Comment by Harry24k** [comment]
> > In that case, the prior distribution would be only used for initialization of weights. Thus, the posteriori is no need to go closer to the priori. Still, weights are drawn from distributions so that we can't call this network as Neural Network, but at the same time, the meaning of using ELBO in the BNN framework is lost. Unfortunately, as I mentioned, I'm not sure this framework is BNN cause I couldn't find any papers treat this framework. Maybe, it should be treated as one of the randomization skills.
> 
> https://github.com/xuanqing94/BayesianDefense/blob/c4c0be9b258f40130b40d6a6e009c459666f2722/main_vi.py#L97.Excuse me, why divide by 100 in this calculation formula.

It seems like they give stability to the model through the addition of step-increasing weight.

**Comment by Harry24k** [comment]
> [https://github.com/kumar-shridhar/PyTorch-BayesianCNN/blob/81e6a354e2638cfad488a139dea4a432d9ad3578/layers/BBB/BBBLinear.py#L57](url).Here I only found that the exp operation is performed on the posterior sigma, but it seems that the exp operation is not performed on the prior.Or am I wrong?

I have no idea why they used rho, but it's same because they used log and exp functions at the same time "torch.log1p(torch.exp(self.W_rho))". It means rho equals sigma mathematically. Meanwhile, in this repository, log_sigma is used for the parameter.

**Comment by Harry24k** [comment]
> As you said above, it is definitely not a traditional neural network without using KLLoss, but it is not sure whether it is a BNN. Then the case of using KLLoss should be BNN. From the demos in the torchbnn project you provided, I tested the "iris" example. I found that the exp operation in the KLLoss calculation formula provided in the project seems to limit the final performance of the built model. I don’t know if I’m doing it properly. If you are interested, you can try it.

I modified previous demo and tested the accuracy of two different KLloss versions as you said, but I only found opposite results. The full code is [here](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/master/demos/Bayesian%20Neural%20Network%20with%20Iris%20Data%20(issues%202).ipynb). One thing is certain, the sensitivity on prior distribution and kl loss are subjects that needs to be studied further.

**Comment by starsky68** [comment]
> > As you said above, it is definitely not a traditional neural network without using KLLoss, but it is not sure whether it is a BNN. Then the case of using KLLoss should be BNN. From the demos in the torchbnn project you provided, I tested the "iris" example. I found that the exp operation in the KLLoss calculation formula provided in the project seems to limit the final performance of the built model. I don’t know if I’m doing it properly. If you are interested, you can try it.
> 
> I modified previous demo and tested the accuracy of two different KLloss versions as you said, but I only found opposite results. The full code is [here](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/master/demos/Sensitivity%20check%20with%20Iris%20Data.ipynb). One thing is certain, the sensitivity on prior distribution and kl loss are subjects that needs to be studied further.

I didn't make it clear last time, the specific klloss I said is like this（(log_sigma_0 ** 2 + (mu_0 - mu_1) ** 2) / (2 * log_sigma_1 ** 2)）. I have just been in touch with BNN related research. Is the exp operation in the klloss formula in the original torchbnn derived by exp obeying (mu, sigma) in the normal distribution? According to the source code you reproduced again, set kl_weight to 0.01, and then use the calculation method of klloss I mentioned above, you can get the result:
-Accuracy: 99.333333%
-CE: 0.03, KL: 0.01
You can try again. If it is as I stated, I hope you can give me your opinion. This is very useful to me. I want to learn more about Bayesian theory and help me complete my paper. Thank you for your patience, I am very grateful for your help.

**Comment by starsky68** [comment]
> > As you said above, it is definitely not a traditional neural network without using KLLoss, but it is not sure whether it is a BNN. Then the case of using KLLoss should be BNN. From the demos in the torchbnn project you provided, I tested the "iris" example. I found that the exp operation in the KLLoss calculation formula provided in the project seems to limit the final performance of the built model. I don’t know if I’m doing it properly. If you are interested, you can try it.
> 
> I modified previous demo and tested the accuracy of two different KLloss versions as you said, but I only found opposite results. The full code is [here](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/master/demos/Sensitivity%20check%20with%20Iris%20Data.ipynb). One thing is certain, the sensitivity on prior distribution and kl loss are subjects that needs to be studied further.

The accuracy does not reach 99.333333% every time, but the frequency of the accuracy value is very high. The accuracy is sometimes 96% or 98%, but the frequency of the accuracy value is relatively low. In any case, the value of KL is very low.

**Comment by starsky68** [comment]
> > As you said above, it is definitely not a traditional neural network without using KLLoss, but it is not sure whether it is a BNN. Then the case of using KLLoss should be BNN. From the demos in the torchbnn project you provided, I tested the "iris" example. I found that the exp operation in the KLLoss calculation formula provided in the project seems to limit the final performance of the built model. I don’t know if I’m doing it properly. If you are interested, you can try it.
> 
> I modified previous demo and tested the accuracy of two different KLloss versions as you said, but I only found opposite results. The full code is [here](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/master/demos/Sensitivity%20check%20with%20Iris%20Data.ipynb). One thing is certain, the sensitivity on prior distribution and kl loss are subjects that needs to be studied further.

I didn't make it clear last time, the specific klloss I said is like this（(log_sigma_0 ** 2 + (mu_0 - mu_1) ** 2) / (2 * log_sigma_1 ** 2)）. I have just been in touch with BNN related research. Is the exp operation in the klloss formula in the original torchbnn derived by exp obeying (mu, sigma) in the normal distribution? 
According to the source code you reproduced again, set kl_weight to 0.01, and then use the calculation method of klloss I mentioned above,you can get the result:
- Accuracy: 99.333333 %
- CE : 0.04, KL : 0.46
The accuracy can be up to 99.333333%, sometimes 97% or 98%, but in any case, the KL value is low.
You can try again. If it is as I stated, I hope you can give me your opinion. This is very useful to me. I want to learn more about Bayesian theory and help me complete my paper. Thank you for your patience, I am very grateful for your help.

**Comment by Harry24k** [comment]
Given the loss function of `(log_sigma_0 ** 2 + (mu_0 - mu_1) ** 2) / (2 * log_sigma_1 ** 2)`, we can ignore the denominator `2 * log_sigma_1 ** 2` because `log_sigma_1` is fixed. Thus, the loss function `log_sigma_0 ** 2 + (mu_0 - mu_1) ** 2` ultimately to reduce (1) `log_sigma_0 ** 2` : the absolute value of log_sigma_0 and (2) `(mu_0 - mu_1) ** 2`  : the difference between mu_0 and mu_1. Mathematically, it is can be expressed as  `E_1[(X-mu_2)**2]` following by [here](https://stats.stackexchange.com/questions/7440/kl-divergence-between-two-univariate-gaussians).

Considering Equation (2) works as same as the original loss function, only Equation (1) is different which makes the sigma of weights to become 1. 
In fact, according to the results [here](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/master/demos/Custom%20KL%20loss%20with%20Iris%20Data.ipynb), compared to the original ones, the log_sigmas of all layers show the value near 0. It means the sigma of layers are set to 1. Actually, it's quite "fluctuating" than the original.

So far, I have only found this much. In my opinion, if the performance of newer one is better than the original, it implies that the sigma of prior should be given like `1.0`. 
I will do more and comment if I find anything. Thanks for your interesting insight.

**Comment by Harry24k** [comment]
> > > As you said above, it is definitely not a traditional neural network without using KLLoss, but it is not sure whether it is a BNN. Then the case of using KLLoss should be BNN. From the demos in the torchbnn project you provided, I tested the "iris" example. I found that the exp operation in the KLLoss calculation formula provided in the project seems to limit the final performance of the built model. I don’t know if I’m doing it properly. If you are interested, you can try it.
> > 
> > 
> > I modified previous demo and tested the accuracy of two different KLloss versions as you said, but I only found opposite results. The full code is [here](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/master/demos/Sensitivity%20check%20with%20Iris%20Data.ipynb). One thing is certain, the sensitivity on prior distribution and kl loss are subjects that needs to be studied further.
> 
> I didn't make it clear last time, the specific klloss I said is like this（(log_sigma_0 ** 2 + (mu_0 - mu_1) ** 2) / (2 * log_sigma_1 ** 2)）. I have just been in touch with BNN related research. Is the exp operation in the klloss formula in the original torchbnn derived by exp obeying (mu, sigma) in the normal distribution?
> According to the source code you reproduced again, set kl_weight to 0.01, and then use the calculation method of klloss I mentioned above,you can get the result:
> 
> * Accuracy: 99.333333 %
> * CE : 0.04, KL : 0.46
>   The accuracy can be up to 99.333333%, sometimes 97% or 98%, but in any case, the KL value is low.
>   You can try again. If it is as I stated, I hope you can give me your opinion. This is very useful to me. I want to learn more about Bayesian theory and help me complete my paper. Thank you for your patience, I am very grateful for your help.

Given the loss function of `(log_sigma_0 ** 2 + (mu_0 - mu_1) ** 2) / (2 * log_sigma_1 ** 2)`, we can ignore the denominator `2 * log_sigma_1 ** 2` because `log_sigma_1` is fixed. Thus, the loss function `log_sigma_0 ** 2 + (mu_0 - mu_1) ** 2` ultimately to reduce (1) `log_sigma_0 ** 2` : the absolute value of log_sigma_0 and (2) `(mu_0 - mu_1) ** 2`  : the difference between mu_0 and mu_1. Mathematically, it is can be expressed as  `E_1[(X-mu_2)**2]` following by [here](https://stats.stackexchange.com/questions/7440/kl-divergence-between-two-univariate-gaussians).

Considering Equation (2) works as same as the original loss function, only Equation (1) is different which makes the sigma of weights to become 1. 
In fact, according to the results [here](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/master/demos/Custom%20KL%20loss%20with%20Iris%20Data.ipynb), compared to the original ones, the log_sigmas of all layers show the value near 0. It means the sigma of layers are set to 1. Actually, it's quite "fluctuating" than the original.

So far, I have only found this much. In my opinion, if the performance of newer one is better than the original, it implies that the sigma of prior should be given like `1.0`. 
I will do more and comment if I find anything. Thanks you for your interesting insight.

**Comment by starsky68** [comment]
> the sigma of prior should be given like `1.0`

I don't quite understand what you said a priori is more like 1.0. Because in the BNN layer we set a priori to 0.05. Can you give me a detailed explanation? Thank you.

**Comment by starsky68** [comment]
> the sigma of prior should be given like `1.0`

I don't quite understand what you said a priori is more like 1.0. Because in the BNN layer we set a priori to 0.05. Can you give me a detailed explanation? Thank you. From the graph you drew, it can be seen that the sigma of weights (that is, the posterior) is closer to 1.0. Is that right?

**Comment by starsky68** [comment]
> the sigma of prior should be given like `1.0`.

I don't quite understand what you said a priori is more like 1.0. Because in the BNN layer we set a priori to 0.05. Can you give me a detailed explanation? Thank you. From the graph you drew, it can be seen that the sigma of weights (that is, the posterior) is closer to 1.0. Is that right? I have another question: The purpose of kl is to narrow the gap between the a priori and the a posteriori, then we set the a priori mu to 0 and the a priori sigma to 0.05, should it be closer to (0, 0.05)? Why is the sigma of weight  closer to 1.0 shown in the picture?

**Comment by Harry24k** [comment]
> > the sigma of prior should be given like `1.0`.
> 
> I don't quite understand what you said a priori is more like 1.0. Because in the BNN layer we set a priori to 0.05. Can you give me a detailed explanation? Thank you. From the graph you drew, it can be seen that the sigma of weights (that is, the posterior) is closer to 1.0. Is that right? I have another question: The purpose of kl is to narrow the gap between the a priori and the a posteriori, then we set the a priori mu to 0 and the a priori sigma to 0.05, should it be closer to (0, 0.05)? Why is the sigma of weight closer to 1.0 shown in the picture?

Sorry for the lack of explanation. I mean, to increase the performance, we can set the sigma of prior as `1.0`. In the picture of last [page](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/master/demos/Custom%20KL%20loss%20with%20Iris%20Data.ipynb), you can see the log_sigmas are close to 0. In other words, sigmas are close to 1.

In addition, the loss function you proposed `(log_sigma_0 ** 2 + (mu_0 - mu_1) ** 2) / (2 * log_sigma_1 ** 2)` IS NOT KL-Divergence at all. As you can see, under the original kl loss, all the log_sigma_0 is closed to -3 to make the sigmas of posterior close to prior's `exp(-3.x)=0.05`.

**Comment by starsky68** [comment]
> > > the sigma of prior should be given like `1.0`.
> > 
> > 
> > I don't quite understand what you said a priori is more like 1.0. Because in the BNN layer we set a priori to 0.05. Can you give me a detailed explanation? Thank you. From the graph you drew, it can be seen that the sigma of weights (that is, the posterior) is closer to 1.0. Is that right? I have another question: The purpose of kl is to narrow the gap between the a priori and the a posteriori, then we set the a priori mu to 0 and the a priori sigma to 0.05, should it be closer to (0, 0.05)? Why is the sigma of weight closer to 1.0 shown in the picture?
> 
> Sorry for the lack of explanation. I mean, to increase the performance, we can set the sigma of prior as `1.0`. In the picture of last [page](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/master/demos/Custom%20KL%20loss%20with%20Iris%20Data.ipynb), you can see the log_sigmas are close to 0. In other words, sigmas are close to 1.
> 
> In addition, the loss function you proposed `(log_sigma_0 ** 2 + (mu_0 - mu_1) ** 2) / (2 * log_sigma_1 ** 2)` IS NOT KL-Divergence at all. As you can see, under the original kl loss, all the log_sigma_0 is closed to -3 to make the sigmas of posterior close to prior's `exp(-3.x)=0.05`.

Thanks for your explanation.

**Comment by starsky68** [comment]
> > > the sigma of prior should be given like `1.0`.
> > 
> > 
> > I don't quite understand what you said a priori is more like 1.0. Because in the BNN layer we set a priori to 0.05. Can you give me a detailed explanation? Thank you. From the graph you drew, it can be seen that the sigma of weights (that is, the posterior) is closer to 1.0. Is that right? I have another question: The purpose of kl is to narrow the gap between the a priori and the a posteriori, then we set the a priori mu to 0 and the a priori sigma to 0.05, should it be closer to (0, 0.05)? Why is the sigma of weight closer to 1.0 shown in the picture?
> 
> Sorry for the lack of explanation. I mean, to increase the performance, we can set the sigma of prior as `1.0`. In the picture of last [page](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/master/demos/Custom%20KL%20loss%20with%20Iris%20Data.ipynb), you can see the log_sigmas are close to 0. In other words, sigmas are close to 1.
> 
> In addition, the loss function you proposed `(log_sigma_0 ** 2 + (mu_0 - mu_1) ** 2) / (2 * log_sigma_1 ** 2)` IS NOT KL-Divergence at all. As you can see, under the original kl loss, all the log_sigma_0 is closed to -3 to make the sigmas of posterior close to prior's `exp(-3.x)=

**Comment by starsky68** [comment]
> > > the sigma of prior should be given like `1.0`.
> > 
> > 
> > I don't quite understand what you said a priori is more like 1.0. Because in the BNN layer we set a priori to 0.05. Can you give me a detailed explanation? Thank you. From the graph you drew, it can be seen that the sigma of weights (that is, the posterior) is closer to 1.0. Is that right? I have another question: The purpose of kl is to narrow the gap between the a priori and the a posteriori, then we set the a priori mu to 0 and the a priori sigma to 0.05, should it be closer to (0, 0.05)? Why is the sigma of weight closer to 1.0 shown in the picture?
> 
> Sorry for the lack of explanation. I mean, to increase the performance, we can set the sigma of prior as `1.0`. In the picture of last [page](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/master/demos/Custom%20KL%20loss%20with%20Iris%20Data.ipynb), you can see the log_sigmas are close to 0. In other words, sigmas are close to 1.
> 
> In addition, the loss function you proposed `(log_sigma_0 ** 2 + (mu_0 - mu_1) ** 2) / (2 * log_sigma_1 ** 2)` IS NOT KL-Divergence at all. As you can see, under the original kl loss, all the log_sigma_0 is closed to -3 to make the sigmas of posterior close to prior's `exp(-3.x)=0.05`.

Can you show me how this function（plot_individual_weight(model)） is implemented?

**Comment by Harry24k** [comment]
> > > > the sigma of prior should be given like `1.0`.
> > > 
> > > 
> > > I don't quite understand what you said a priori is more like 1.0. Because in the BNN layer we set a priori to 0.05. Can you give me a detailed explanation? Thank you. From the graph you drew, it can be seen that the sigma of weights (that is, the posterior) is closer to 1.0. Is that right? I have another question: The purpose of kl is to narrow the gap between the a priori and the a posteriori, then we set the a priori mu to 0 and the a priori sigma to 0.05, should it be closer to (0, 0.05)? Why is the sigma of weight closer to 1.0 shown in the picture?
> > 
> > 
> > Sorry for the lack of explanation. I mean, to increase the performance, we can set the sigma of prior as `1.0`. In the picture of last [page](https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/master/demos/Custom%20KL%20loss%20with%20Iris%20Data.ipynb), you can see the log_sigmas are close to 0. In other words, sigmas are close to 1.
> > In addition, the loss function you proposed `(log_sigma_0 ** 2 + (mu_0 - mu_1) ** 2) / (2 * log_sigma_1 ** 2)` IS NOT KL-Divergence at all. As you can see, under the original kl loss, all the log_sigma_0 is closed to -3 to make the sigmas of posterior close to prior's `exp(-3.x)=0.05`.
> 
> Can you show me how this function（plot_individual_weight(model)） is implemented?

I used my custom utils : [https://github.com/Harry24k/pytorch-custom-utils](https://github.com/Harry24k/pytorch-custom-utils) :)
