### ISSUE TITLE
Initialization and reparameterization

### ISSUE THREAD

**Issue by starsky68** [Harry24k/bayesian-neural-network-pytorch#3]
https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/41aced05e68d879f5d3a7c74f1a90d8e19da84c9/torchbnn/modules/linear.py#L55.
1. Excuse me, is it necessary to use "fill_(self.prior_log_sigma)" to initialize the posterior sigma in BNN? Can it be changed? Does it conform to BNN theory if it is changed?

https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/41aced05e68d879f5d3a7c74f1a90d8e19da84c9/torchbnn/modules/linear.py#L86
2. Must this method be used in reparameterization techniques? That is z=u+exp(sigma)*eps. Can this reparameterized calculation method be changed? Is it consistent with BNN theory after the change?

**Comment by Harry24k** [comment]
> https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/41aced05e68d879f5d3a7c74f1a90d8e19da84c9/torchbnn/modules/linear.py#L55
> 
> .
> 1. Excuse me, is it necessary to use "fill_(self.prior_log_sigma)" to initialize the posterior sigma in BNN? Can it be changed? Does it conform to BNN theory if it is changed?
> 
> https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/41aced05e68d879f5d3a7c74f1a90d8e19da84c9/torchbnn/modules/linear.py#L86
> 
> 
> 2. Must this method be used in reparameterization techniques? That is z=u+exp(sigma)*eps. Can this reparameterized calculation method be changed? Is it consistent with BNN theory after the change?

Sorry for the late reply.

1. You can change that. This is just one way of initialization.

2. The reparametrization techniques must be maintained. It is the main part of BNN.

**Comment by starsky68** [comment]
> > https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/41aced05e68d879f5d3a7c74f1a90d8e19da84c9/torchbnn/modules/linear.py#L55
> > 
> > .
> > 
> > 1. Excuse me, is it necessary to use "fill_(self.prior_log_sigma)" to initialize the posterior sigma in BNN? Can it be changed? Does it conform to BNN theory if it is changed?
> > 
> > https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/41aced05e68d879f5d3a7c74f1a90d8e19da84c9/torchbnn/modules/linear.py#L86
> > 
> > 
> > 1. Must this method be used in reparameterization techniques? That is z=u+exp(sigma)*eps. Can this reparameterized calculation method be changed? Is it consistent with BNN theory after the change?
> 
> Sorry for the late reply.
> 
> 1. You can change that. This is just one way of initialization.
> 2. The reparametrization techniques must be maintained. It is the main part of BNN.

**Comment by starsky68** [comment]
> > > https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/41aced05e68d879f5d3a7c74f1a90d8e19da84c9/torchbnn/modules/linear.py#L55
> > > 
> > > .
> > > 
> > > 1. Excuse me, is it necessary to use "fill_(self.prior_log_sigma)" to initialize the posterior sigma in BNN? Can it be changed? Does it conform to BNN theory if it is changed?
> > > 
> > > https://github.com/Harry24k/bayesian-neural-network-pytorch/blob/41aced05e68d879f5d3a7c74f1a90d8e19da84c9/torchbnn/modules/linear.py#L86
> > > 
> > > 
> > > 1. Must this method be used in reparameterization techniques? That is z=u+exp(sigma)*eps. Can this reparameterized calculation method be changed? Is it consistent with BNN theory after the change?
> > 
> > 
> > Sorry for the late reply.
> > 
> > 1. You can change that. This is just one way of initialization.
> > 2. The reparametrization techniques must be maintained. It is the main part of BNN.
